#!/bin/bash

CURDIR=`pwd`

cd src/Mint-Y
./build-themes.py

cd $CURDIR

sudo rm -rf /usr/share/themes/Mint-Yz-Base
sudo cp -R usr/share/themes/Mint-Yz-Base /usr/share/themes/Mint-Yz-Base

# Force refresh
gsettings set org.cinnamon.desktop.interface gtk-theme 'Mint-Y'
gsettings set org.cinnamon.desktop.interface gtk-theme 'Mint-Yz-Base'
